name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run jest
        env:
          CI: true
  e2e:
    runs-on: ubuntu-latest
    steps:
      - run: echo terraform tests
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy